/* All the code in this file was generated by OS Openspace Map Builder, before being edited to improve functionality. */

function loadMap(month) {

	/* Set the chosen month to be the first available on page load, otherwise set it to the month selected from the menu. */
	var chosenMonth;
	var walkList = document.getElementsByClassName("walkSwitcher");
	if (month === undefined) {
		chosenMonth = walkList[0].id;
	} else {
		chosenMonth = month;
	}

	/* Ensure that the 'mapElement' div is empty in readiness for a new map. */
	document.getElementById("routeMap").innerHTML = "";

	/* Variables to initialise the map, generated by OS Openspace Map Builder. Variable osMap created in remotely hosted OS Openspace file basicmap.js. */
	var options = {resolutions: [2500, 1000, 500, 200, 100, 50, 25, 10, 5, 4, 2.5, 2, 1]};
	osMap = new OpenSpace.Map('routeMap', options);

	/* Object containing the map reference data for each currently available map. Data generated by OS Openspace Map Builder and then re-organised into objects. */
	var mapData = {
		"nov17": {
			center: {x:255765, y:70700},
			start: {x:254695, y:69250},
			route: [
				{x:254695, y:69250},
				{x:254885, y:69440},
				{x:254915, y:69760},
				{x:254845, y:70220},
				{x:254805, y:70360},
				{x:254655, y:70470},
				{x:254525, y:70610},
				{x:254515, y:70720},
				{x:254565, y:70920},
				{x:254675, y:71040},
				{x:254835, y:71090},
				{x:254955, y:71130},
				{x:255155, y:71260},
				{x:255315, y:71340},
				{x:255435, y:71340},
				{x:255575, y:71480},
				{x:255595, y:71700},
				{x:255505, y:71900},
				{x:255345, y:72050},
				{x:255385, y:72190},
				{x:255545, y:72240},
				{x:255765, y:72240},
				{x:256015, y:72260},
				{x:256255, y:72420},
				{x:256375, y:72580},
				{x:256755, y:72620},
				{x:256955, y:72640},
				{x:257105, y:72460},
				{x:257245, y:72210},
				{x:257325, y:71890},
				{x:257335, y:71670},
				{x:257245, y:71410},
				{x:257185, y:71280},
				{x:256995, y:71120},
				{x:256895, y:71050},
				{x:256915, y:70920},
				{x:256905, y:70670},
				{x:256885, y:70550},
				{x:256805, y:70460},
				{x:256755, y:70390},
				{x:256645, y:70210},
				{x:256555, y:69910},
				{x:256485, y:69590},
				{x:256405, y:69540},
				{x:256115, y:69530},
				{x:255965, y:69520},
				{x:255735, y:69450},
				{x:255455, y:69340},
				{x:255315, y:69280},
				{x:255255, y:69250},
				{x:255195, y:69230},
				{x:255025, y:69230},
				{x:254865, y:69220},
				{x:254705, y:69260},
				{x:254695, y:69250},
			],
		},
		"dec17": {
			center: {x:258380, y:64435},
			start: {x:257000, y:63195},
			route: [
				{x:257000, y:63195},
				{x:257150, y:63055},
				{x:257460, y:63215},
				{x:257700, y:63395},
				{x:257680, y:63655},
				{x:257700, y:63715},
				{x:257830, y:63615},
				{x:257950, y:63775},
				{x:258050, y:63665},
				{x:258280, y:63545},
				{x:258500, y:63455},
				{x:258740, y:63385},
				{x:259020, y:63105},
				{x:259340, y:63395},
				{x:259740, y:63735},
				{x:259910, y:64065},
				{x:260230, y:64545},
				{x:259520, y:65265},
				{x:259150, y:65515},
				{x:258670, y:66075},
				{x:258540, y:65985},
				{x:258270, y:65985},
				{x:258190, y:65995},
				{x:258140, y:65885},
				{x:258150, y:65805},
				{x:257990, y:65865},
				{x:257850, y:65835},
				{x:257850, y:65655},
				{x:257760, y:65365},
				{x:257770, y:65115},
				{x:257700, y:65005},
				{x:257610, y:65045},
				{x:257250, y:65015},
				{x:257190, y:64905},
				{x:257100, y:64635},
				{x:257110, y:64365},
				{x:257100, y:63885},
				{x:257100, y:63725},
				{x:257040, y:63405},
				{x:257000, y:63195},
			],
		},
		"jan18": {
			center: {x:258505, y:69755},
			start: {x:256900, y:69275},
			route: [
				{x:256900, y:69275},
				{x:257180, y:69305},
				{x:257800, y:69315},
				{x:257980, y:69265},
				{x:258200, y:69285},
				{x:258980, y:69415},
				{x:259560, y:69525},
				{x:260010, y:69805},
				{x:260410, y:69915},
				{x:260400, y:70045},
				{x:260290, y:70365},
				{x:260030, y:70485},
				{x:259940, y:70605},
				{x:259850, y:70605},
				{x:259670, y:70615},
				{x:259430, y:70445},
				{x:259090, y:70355},
				{x:258780, y:70325},
				{x:258580, y:70415},
				{x:258520, y:70415},
				{x:258270, y:70445},
				{x:258120, y:70215},
				{x:258000, y:70115},
				{x:257780, y:70115},
				{x:257520, y:70075},
				{x:257320, y:69985},
				{x:257100, y:69795},
				{x:257100, y:69635},
				{x:256900, y:69475},
				{x:256830, y:69495},
				{x:256780, y:69425},
				{x:256920, y:69275},
				{x:256900, y:69275},
			],
		},
		"feb18": {
			center: {x:225435, y:72915},
			start: {x:225930, y:71095},
			route: [
				{x:225930, y:71095},
				{x:226070, y:71175},
				{x:226150, y:71445},
				{x:226220, y:71565},
				{x:226270, y:71805},
				{x:226180, y:71975},
				{x:225950, y:72185},
				{x:225730, y:72325},
				{x:225740, y:72565},
				{x:225660, y:73095},
				{x:225860, y:73245},
				{x:225950, y:73595},
				{x:226010, y:73785},
				{x:225780, y:74425},
				{x:225420, y:74905},
				{x:225300, y:74775},
				{x:225280, y:74585},
				{x:225110, y:74435},
				{x:225020, y:74365},
				{x:224820, y:74275},
				{x:224800, y:73965},
				{x:224870, y:73625},
				{x:225150, y:73375},
				{x:225370, y:73225},
				{x:225320, y:73055},
				{x:225420, y:72975},
				{x:225410, y:72615},
				{x:225390, y:72435},
				{x:225280, y:72265},
				{x:225430, y:72155},
				{x:225440, y:71925},
				{x:225670, y:71415},
				{x:225830, y:71375},
				{x:225830, y:71265},
				{x:225930, y:71095},
			],
		},
		"mar18": {
			center: {x:243670, y:50400},
			start: {x:243155, y:50310},
			route: [
				{x:243155, y:50310},
				{x:243365, y:50210},
				{x:243305, y:50160},
				{x:243495, y:49870},
				{x:243815, y:49650},
				{x:244065, y:49410},
				{x:244105, y:49160},
				{x:244165, y:48830},
				{x:243875, y:48890},
				{x:243525, y:48950},
				{x:243075, y:48950},
				{x:242645, y:48970},
				{x:242375, y:48830},
				{x:242205, y:48710},
				{x:242125, y:48570},
				{x:241915, y:48470},
				{x:241895, y:48840},
				{x:241805, y:48940},
				{x:242105, y:49210},
				{x:242245, y:49790},
				{x:242385, y:49850},
				{x:242435, y:49850},
				{x:242695, y:50010},
				{x:242885, y:50130},
				{x:243045, y:50240},
				{x:243155, y:50320},
				{x:243315, y:50300},
				{x:243335, y:50300},
				{x:243405, y:50360},
				{x:243485, y:50580},
				{x:244035, y:51100},
				{x:244375, y:51320},
				{x:244735, y:51430},
				{x:245015, y:51570},
				{x:245385, y:51610},
				{x:245445, y:51790},
				{x:245555, y:51670},
				{x:245825, y:51790},
				{x:245885, y:51960},
				{x:245875, y:52210},
				{x:245855, y:52420},
				{x:245765, y:52440},
				{x:245535, y:52170},
				{x:245365, y:52280},
				{x:245255, y:52380},
				{x:245055, y:52420},
				{x:244915, y:52250},
				{x:244555, y:52050},
				{x:244385, y:51820},
				{x:244215, y:51790},
				{x:244075, y:51710},
				{x:243935, y:51680},
				{x:243965, y:51570},
				{x:243835, y:51320},
				{x:243905, y:51180},
				{x:243855, y:51090},
				{x:243535, y:50750},
				{x:243395, y:50650},
				{x:243415, y:50440},
				{x:243355, y:50320},
				{x:243135, y:50310},
			],
		},
		"apr18": {
			center: {x:254284, y:86838},
			start: {x:252509, y:85393},
			route: [
				{x:252509, y:85393},
				{x:252919, y:85683},
				{x:253059, y:85713},
				{x:252969, y:86183},
				{x:253029, y:86313},
				{x:253179, y:86403},
				{x:253429, y:86833},
				{x:253649, y:87063},
				{x:253689, y:87263},
				{x:253709, y:87473},
				{x:253859, y:87713},
				{x:254219, y:87943},
				{x:254379, y:88083},
				{x:254479, y:88403},
				{x:254549, y:88793},
				{x:254659, y:88483},
				{x:254929, y:88123},
				{x:255039, y:87773},
				{x:254999, y:87483},
				{x:255269, y:87233},
				{x:255219, y:86833},
				{x:255469, y:86653},
				{x:255909, y:86503},
				{x:255809, y:86273},
				{x:255719, y:86113},
				{x:255409, y:85543},
				{x:255279, y:85343},
				{x:254669, y:85373},
				{x:254489, y:85443},
				{x:253909, y:85653},
				{x:253779, y:85593},
				{x:253579, y:85533},
				{x:253249, y:85753},
				{x:253079, y:85723},
				{x:252849, y:85653},
				{x:252579, y:85453},
				{x:252509, y:85393},
			],
		},
	};

	/* Variables to create the route line, generated by OS Openspace Map Builder. */
	var linesLayer, points, lineFeature, lineString, routeMarkersLayer, routepos, routesize, routeoffset, routeicon;
	var style_blue = {strokeColor: "#0000cc", strokeOpacity: 0.5, strokeWidth: 4.5};

	/* Function to configure map options, defined in OS Openspace file basicmap.js. */
	setglobaloptions();

	/* Code to set the centre point of the map and the zoom layer, generated by OS Openspace Map Builder. */
	osMap.setCenter(new OpenSpace.MapPoint(mapData[chosenMonth].center.x, mapData[chosenMonth].center.y),7);
	var linesLayer = osMap.getVectorLayer();

	/* Empty array to hold map reference points for route map. */
	var points = [];

	/* Loop to push points into route array. */
	for (var i = 0; i < mapData[chosenMonth].route.length; i++) {
		points.push(new OpenLayers.Geometry.Point(mapData[chosenMonth].route[i].x, mapData[chosenMonth].route[i].y));
	}

	/* Variables to create a polyline feature from the array of points, generated by OS Openspace Map Builder. */
	var routeMarkersLayer = new OpenLayers.Layer.Markers("Route Markers");
	var lineString = new OpenLayers.Geometry.LineString(points);
	var lineFeature = new OpenLayers.Feature.Vector(lineString, null, style_blue);
	linesLayer.addFeatures([lineFeature]);

	/* Variables to create and position the start/finish marker, generated by OS Openspace Map Builder. */
	var routepos = new OpenSpace.MapPoint(mapData[chosenMonth].start.x,mapData[chosenMonth].start.y);
	var routesize = new OpenLayers.Size(33,45);
	var routeoffset = new OpenLayers.Pixel(-5,-37);
	var routeicon = new OpenSpace.Icon('https://openspace.ordnancesurvey.co.uk/osmapapi/img_versions/img_1.1/mapbuilder/routemarker-startend.png', routesize, routeoffset, null, null);
	routeMarkersLayer.addMarker(new OpenLayers.Marker(routepos, routeicon));
	osMap.addLayer(routeMarkersLayer);

}

loadMap();